### ISSUE TITLE
Guest edit option (deactivation)

### ISSUE THREAD

**Issue by ahmad-ml** [nifty-apps/booking-dei-web#18]
### Here is a sample mutation of guest deactivation. 

```
mutation UpdateContact {
    updateContact(
        updateContactInput: {
            _id: "6512d140aa7c98828e5c2899"
            detactivatedAt: "2023-10-16"
            hotel: "64d0a1d008291a484b015d0b"
        }
    ) {
        _id
        name
        phone
        idType
        idNo
        address
        hotel
        type
        detactivatedAt
    }
}
```

## Task

1. Add a deactivation button with a confirmation pop-up.
2. When confirmation is pressed use this update mutation query to deactivate the customer
3. Add a toggle button on the guest look-up to see the deactivated contacts and add an option to activate again. 

![image](https://github.com/nifty-apps/booking-dei-web/assets/37737000/34f280ee-793e-4511-b27c-85ad81b634da)

4. Update the booking summary function so that deactivated customers do not appear while on the booking summary page. 

![image](https://github.com/nifty-apps/booking-dei-web/assets/37737000/24984126-3bb6-4e89-ae38-a95553d6d784)

**Comment by ekram2d** [comment]
![image](https://github.com/nifty-apps/booking-dei-web/assets/68508046/14549cbd-b35c-4a83-af13-73f98ad6a861)
if we use single button then how to find which id number is deactivated and updated
